# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata', 'jekyll-category-archive-plugin']

# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            TCP
tagline:          cybersecurity blog
description:      "一个立志于翻译优秀网络安全博文的中文博客"
url:              https://jesseei.github.io
baseurl:          /

author:
  name:           'tcp'
  url:            tacapng@hotmail.com
  
paginate:         1

# Custom vars
version:          1.0.1

github:
  repo:           https://github.com/jesseei
  
# author info
email:            tacapng@hotmail.com
