# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-category-archive-plugin

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            CyberSecurity
tagline:          cybersecurity blog
description:      "一个立志于翻译优秀网络安全博文的中文博客"
url:              https://jesseei.github.io
baseurl:          /

author:
  name:           'tcp'
  url:            tacapng@hotmail.com
  
paginate:         3

# Custom vars
version:          2.0.1

github:
  repo:           https://github.com/jesseei
  
# author info
email:            tacapng@hotmail.com
